% ========== Definition of moments to target ==============================



moments = struct;
moments.names = {...
    'Avg. of consumption growth';...
    'Avg. of inflation';...
    'Std. dev. of consumption growth';...
    'Std. dev. of output gap';...
    'Std. dev. of inflation';...
    'AC(1) of consumption growth';...
    'AC(1) of output gap';...
    'AC(1) of inflation';...
    'Min of ratio E(RA)/SD(RA)';
    'Max of E(RA)';...
    'Max correlation between output gap and RA';...
    'Avg 10-year real yield';...
    'Avg 3-month nominal yield';...
    'Avg 10-year nominal yield';...
    'Std. dev. of 10-year real rate';...
    'Std. dev. of 10-year nominal rate';...
    'Avg slope of real yield curve (2-10 yrs)';
    'Avg slope of nominal yield curve (2-10 yrs)';...
    'Std. dev. of 2-year real rate';...
    'Std. dev. of 2-year nominal rate';...
    'AC(1) of 10-year real yield';...
    'AC(1) of 10-year nominal rate';...
    'Std. dev. of 10-year nominal term premium';...
    'Correl. 10-year real rate and output gap'
    };
moments.values = [...
    %mean(data_bis(:,find(strcmp(data_names,{'real GDP'}))),'omitnan')/100;...
    mean(data_bis(:,find(strcmp(data_names,{'Consumption growth'}))),'omitnan')/100;...
    mean(data_bis(:,find(strcmp(data_names,{'CPI inflation'}))),'omitnan')/100;...
    %std(data_bis(:,find(strcmp(data_names,{'real GDP'}))),'omitnan')/100;...
    std(data_bis(:,find(strcmp(data_names,{'Consumption growth'}))),'omitnan')/100;...
    std(data_bis(:,find(strcmp(data_names,{'Output gap'}))),'omitnan');...
    std(data_bis(:,find(strcmp(data_names,{'CPI inflation'}))),'omitnan')/100;...
    %autocorX(data_bis(:,find(strcmp(data_names,{'real GDP'}))),1);...
    autocorX(data_bis(:,find(strcmp(data_names,{'Consumption growth'}))),1);...
    autocorX(data_bis(:,find(strcmp(data_names,{'Output gap'}))),1);...
    autocorX(data_bis(:,find(strcmp(data_names,{'CPI inflation'}))),1);...
    3;...
    20;...
    0;...
    mean(data_bis(:,find(strcmp(data_names,{'TIPSY10'}))),'omitnan')/100;...
    mean(data_bis(:,find(strcmp(data_names,{'YIELD3M'}))),'omitnan')/100;...
    mean(data_bis(:,find(strcmp(data_names,{'YIELD10'}))),'omitnan')/100;...
    std(data_bis(:,find(strcmp(data_names,{'TIPSY10'}))),'omitnan')/100;...
    std(data_bis(:,find(strcmp(data_names,{'YIELD10'}))),'omitnan')/100;...
    mean(data_bis(:,find(strcmp(data_names,{'real slope'}))),'omitnan')/100;...
    mean(data_bis(:,find(strcmp(data_names,{'nominal slope'}))),'omitnan')/100;...
    std(data_bis(:,find(strcmp(data_names,{'TIPSY02'}))),'omitnan')/100;...
    std(data_bis(:,find(strcmp(data_names,{'YIELD02'}))),'omitnan')/100;...
    autocorX(data_bis(:,find(strcmp(data_names,{'TIPSY10'}))),1);...
    autocorX(data_bis(:,find(strcmp(data_names,{'YIELD10'}))),1);...
    std(data_bis(:,find(strcmp(data_names,{'10-year nom. term premium'}))),'omitnan')/100;...
    corr(data_bis(:,find(strcmp(data_names,{'TIPSY10'}))),...
    data_bis(:,find(strcmp(data_names,{'Output gap'}))),'Rows','complete')...
    ];
moments.weights = [...
    100; ... %'Avg. of GDP growth';...
    100; ... %'Avg. of inflation';...
    1; ... %'Std. dev. of GDP growth';...
    1; ... %'Std. dev. of output gap';...
    1; ... %'Std. dev. of inflation';...
    1; ... %'AC(1) of GDP growth';...
    1; ... %'AC(1) of output gap';...
    0; ... %'AC(1) of inflation';...
    1; ... %'Min of ratio E(RA)/SD(RA)';
    1; ... %'Max of E(RA)';...
    1; ... %'Max correlation between output gap and RA';...
    100; ... %'Avg 10-year real yield';...
    100; ... %'Avg 3-month nominal yield';...
    100; ... %'Avg 10-year nominal yield';...
    100; ... %'Std. dev. of 10-year real rate';...
    100; ... %'Std. dev. of 10-year nominal rate';...
    10000; ... %'Avg slope of real yield curve (2-10 yrs)';
    1000; ... %'Avg slope of nominal yield curve (2-10 yrs)';...
    100; ... %'Std. dev. of 2-year real rate';...
    100; ... %'Std. dev. of 2-year nominal rate';...
    1; ... %'AC(1) of 10-year real yield';...
    1; ... %'AC(1) of 10-year nominal rate';...
    10000; ... %'Std. dev. of 10-year nominal term premium';...
    .1'%Correl. 10-year real rate and output gap'
    ];
moments.indic_min = 0*moments.values;
%moments.indic_min(9) = 1;
moments.indic_max = 0*moments.values;
moments.indic_max(10:11) = 1;
